### ISSUE TITLE
'Open-source' vs 'open source'

### ISSUE THREAD

**Issue by jnicho02** [osmfoundation/sotm2019-booklet#23]
'Open-source' with a hyphen means "released under a license in which the copyright holder grants users the rights to study, change, and distribute the software to anyone and for any purpose".

'Open source' without a hyphen means "source code is published so that people may see it"

**Comment by Nakaner** [comment]
I doubt that readers are aware of the great difference caused by a hyphen. Therefore, I cannot guess what the authors of the abstracts thought. That's why I will unify all variations of "open source" to "open-source" with a hyphen.

The programme committee is quite anti-proprietary this year, so I assume that they were quite strict w.r.t. open-washing things (see the [call for papers](https://2019.stateofthemap.org/calls/general/) for reference).
