### ISSUE TITLE
improvements to local venue map

### ISSUE THREAD

**Issue by tyrasd** [osmfoundation/sotm2019-booklet#7]
It would be nice if the "zoomed in" map of the campus, conference venue and surroundings showed a bit more detail, e.g. in terms of points of interest.

I would try to include stuff like:

* restaurants / bakeries / shops
* the wheelchair-accessible entrance
* bike sharing stations
* trees
* housenumbers, names of buildings

Also please:

* mark access to the group photo: it is best to enter from the north
* fix order of room "names" of mathematikon building: Seminarraum C is the northernmost one

In addition it would be nice to somehow mark the current construction sites near the venue building. e.g. some paths fromt he Chemie Hörsaalgebäude towards the West or South cannot be used at the moment and are fenced off.

**Comment by Nakaner** [comment]
> It would be nice if the "zoomed in" map of the campus, conference venue and surroundings showed a bit more detail, e.g. in terms of points of interest.
> 
> I would try to include stuff like:
> 
>     * restaurants / bakeries / shops

I will add these POIs manually (and disable the supermarkets in the style).

>     * the wheelchair-accessible entrance

I will add such an icon.

>     * bike sharing stations
> 
>     * trees

Are you sure that all or almost all trees are mapped in that part of the campus? I render with scale factor 3, i.e. I am 2 zoom levels lower than the bounding box and size of the features might suggest. Trees are not rendered at that zoom level and I wonder if they are that helpful.

>     * housenumbers, names of buildings

Grrrr, I disabled the buildings-text layer in OSM Carto but it seems that I have to do more patching (I wanted to get rid of all the "XY-Institut" labels because I their signs aren't that large in reality and easy to spot from far away).

> Also please:
> 
>     * mark access to the group photo: it is best to enter from the north

I wanted to do that as well but I doubt whether people really understand any symbol we use for that purpose. If I remember right, you can enter the upper part of the courtyard from the foyer (but not into the other direction) and the entrance to the courtyard is from the north where people from the Chemie-Hörsaalgebäude (catering) will come from.

In my first draft, I placed "Mathematikon" in the southern part of the southern building until I decided to add the label "poster event" there. That's why I can't place an arrow pointing into the courtyard except I rotate the "Mathematikon" label by 90°. :-(

>     * fix order of room "names" of mathematikon building: Seminarraum C is the northernmost one

Thanks. Is B the one in the middle?

> In addition it would be nice to somehow mark the current construction sites near the venue building. e.g. some paths fromt he Chemie Hörsaalgebäude towards the West or South cannot be used at the moment and are fenced off.

Add the construction sites to the OSM and my rendering database will have them within 10 minutes.

**Comment by tyrasd** [comment]
> Are you sure that all or almost all trees are mapped in that part of the campus?

I can't guarantee that every single tree is mapped, but I believe the coverage is quite good.

> I wanted to do that as well but I doubt whether people really understand any symbol we use for that purpose.

maybe just place the photo icon a bit further north? approximately here: https://osm.org/go/0DwYyjcem?m=

> Thanks. Is B the one in the middle?

Yes.

> Add the construction sites to the OSM and my rendering database will have them within 10 minutes.

Ok, give me a few days.

**Comment by tyrasd** [comment]
>> Add the construction sites to the OSM and my rendering database will have them within 10 minutes.
>
> Ok, give me a few days.

done: http://overpass-turbo.eu/s/LIL
